CREATE TABLE ARTICLE(
    ARTICLE_NO NUMBER,
    WRITER_ID VARCHAR2(50),
    WRITER_NAME VARCHAR2(150),
    TITLE VARCHAR2(300),
    REGDATE DATE,
    MODDATE DATE,
    READ_CNT NUMBER,
    CONSTRAINT PK_ARTICLE PRIMARY KEY(ARTICLE_NO)
);

CREATE TABLE ARTICLE_CONTENT(
    ARTICLE_NO NUMBER PRIMARY KEY,
    CONTENT VARCHAR2(3000)
);