CREATE TABLE MEMBER(
    MEMBERID VARCHAR2(50),
    NAME VARCHAR2(150),
    PASSWORD VARCHAR2(100),
    REGDATE DATE,
    CONSTRAINT PK_MEMBER PRIMARY KEY(MEMBERID)
);

COMMENT ON TABLE MEMBER IS '회원';

COMMENT ON COLUMN MEMBER.MEMBERID IS '회원 아이디';
COMMENT ON COLUMN MEMBER.NAME IS '회원 이름';
COMMENT ON COLUMN MEMBER.PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBER.REGDATE IS '등록일';

COMMIT;