--카멜 변환 함수
CREATE OR REPLACE FUNCTION FN_GETCAMEL(COLUMN_NAME IN VARCHAR2)
    RETURN VARCHAR2
IS
    RSLT VARCHAR2(30);
BEGIN
    SELECT LOWER(SUBSTR(REPLACE(INITCAP(COLUMN_NAME),'_'),1,1))
    || SUBSTR(REPLACE(INITCAP(COLUMN_NAME),'_'),2) INTO RSLT
    FROM DUAL;
    
    RETURN RSLT;
END;
commit;
--<input type='text' value='siteNum' /><br/>
--private int siteNum;
SELECT COLUMN_NAME
        , DATA_TYPE
        , '<input type=''text'' name='''||FN_GETCAMEL(COLUMN_NAME) ||''' /><br/>' JSP
        , CASE WHEN DATA_TYPE='NUMBER' THEN 'private int ' || FN_GETCAMEL(COLUMN_NAME) || ';'
               WHEN DATA_TYPE IN('VARCHAR2','CHAR') THEN 'private String ' || FN_GETCAMEL(COLUMN_NAME) || ';'
               WHEN DATA_TYPE ='DATE' THEN 'private Date ' || FN_GETCAMEL(COLUMN_NAME) || ';'
               ELSE 'private String ' || FN_GETCAMEL(COLUMN_NAME) || ';'
          END AS CAMEL_CASE,
          '<result column="' || COLUMN_NAME ||'" property="' || FN_GETCAMEL(COLUMN_NAME) ||'" />' RESULTMAP
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CUS';

SELECT * FROM ALL_TAB_COLUMNS;
SELECT * FROM ALL_CONS_COLUMNS;

--SITE_NUM	NUMBER	사업장 번호	<input type='text' name='siteNum' /><br/>	private int siteNum;
SELECT A.COLUMN_NAME
        , A.DATA_TYPE
        , (SELECT B.COMMENTS FROM ALL_COL_COMMENTS B WHERE B.TABLE_NAME = A.TABLE_NAME AND B.COLUMN_NAME = A.COLUMN_NAME) COMMENTS
        , '<input type=''text'' name='''||FN_GETCAMEL(COLUMN_NAME) ||''' /><br/>' JSP
        , CASE WHEN DATA_TYPE='NUMBER' THEN 'private int ' || FN_GETCAMEL(COLUMN_NAME) || ';'
               WHEN DATA_TYPE IN('VARCHAR2','CHAR') THEN 'private String ' || FN_GETCAMEL(COLUMN_NAME) || ';'
               WHEN DATA_TYPE ='DATE' THEN 'private Date ' || FN_GETCAMEL(COLUMN_NAME) || ';'
               ELSE 'private String ' || FN_GETCAMEL(COLUMN_NAME) || ';'
          END CAMEL_CASE     
FROM ALL_TAB_COLUMNS A
WHERE A.TABLE_NAME = 'EMP';

--직원번호(연도월001) 202108001
--직원 번호를 6자리만 잘라낸것과 현재날짜 '202108'이 같은것 중에 제일 큰거를 찾아서 1을 더해줌
SELECT NVL(MAX(EMP_NUM),TO_CHAR(SYSDATE,'YYYYMM') || '000') + 1
FROM EMP
WHERE SUBSTR(EMP_NUM,6) = TO_CHAR(SYSDATE,'YYYYMM');

INSERT INTO EMP(EMP_NUM, NM, ADDR, PNE, SAL)
VALUES(
(SELECT NVL(MAX(EMP_NUM),TO_CHAR(SYSDATE,'YYYYMM') || '000') + 1
FROM EMP
WHERE SUBSTR(EMP_NUM,6) = TO_CHAR(SYSDATE,'YYYYMM')),
'홍길동', '대전광역시 중구123', '010-123-1234', 200);
);

SELECT TO_CHAR(SYSDATE,'YYYYMM') || '001' FROM DUAL

ROLLBACK


SELECT SUBSTR(EMP_NUM,1,6),TO_CHAR(SYSDATE, 'YYYYMM')  FROM EMP;

SELECT EMP_NUM, NM, ADDR, PNE, SAL 
FROM EMP
WHERE EMP_NUM = '202108003'

UPDATE EMP
SET NM='',ADDR='',PNE='',SAL=''
WHERE EMP_NUM = '202108003'


SELECT *
FROM KOREA.MEMBER;

SELECT MEM_NAME, MEM_ZIP || ' ' || MEM_ADD1 || ' ' || MEM_ADD2, MEM_HP, 200
FROM KOREA.MEMBER;

SELECT ROW_NUMBER() OVER (ORDER BY EMP_NUM DESC) RNUM,
EMP_NUM, NM, ADDR, PNE, SAL
FROM EMP;

SELECT MAX(EMP_NUM) FROM EMP;

SELECT TO_CHAR(SYSDATE,'YYYYMM') || LPAD(SEQ_TEST.NEXTVAL,3,0) FROM DUAL;

--KOREA계정의 MEMBER테이블 내용을 EMP테이블로 넣기
INSERT INTO EMP(EMP_NUM, NM, ADDR, PNE, SAL)
SELECT (TO_CHAR(SYSDATE,'YYYYMM') || LPAD(SEQ_TEST.NEXTVAL,3,0))
, MEM_NAME, MEM_ZIP || ' ' || MEM_ADD1 || ' ' || MEM_ADD2, MEM_HP, 200
FROM KOREA.MEMBER;

commit
--시퀀스 생성
CREATE SEQUENCE SEQ_TEST
START WITH 3
INCREMENT BY 1;

--시퀀스 삭제
DROP SEQUENCE SEQ_TEST;

--잘못생성한거 지움
DELETE FROM EMP
WHERE EMP_NUM > 202108002;
;
/
--dasuri 계정의 MEMBER_TEMP 테이블을 생성할 때 korea 계정의 MEMBER 테이블의
--스키마와 데이터를 가지고 생성함
CREATE TABLE MEMBER_TEMP
AS
SELECT * FROM KOREA.MEMBER;

SELECT * FROM MEMBER_TEMP;

DELETE FROM MEMBER_TEMP;

INSERT INTO MEMBER_TEMP(MEM_ID, MEM_PASS, MEM_NAME)
SELECT MEM_ID, MEM_PASS, MEM_NAME FROM KOREA.MEMBER;

ROLLBACK
;
/

SELECT T.*
FROM
(
    SELECT ROW_NUMBER() OVER (ORDER BY EMP_NUM DESC) RNUM,
    EMP_NUM, NM, ADDR, PNE, SAL
    FROM EMP
) T
WHERE T.RNUM BETWEEN 1 AND 10

UPDATE EMP
SET PWD='1234'

COMMIT

SELECT EMP_NUM, NM, ADDR, PNE, SAL, PWD
FROM EMP
WHERE EMP_NUM = '202108001' AND PWD='1234'
;
/

SELECT *
FROM CUS


--INSERT INTO CUS(CUS_NUM, CUS_NM, ADDR, PNE)
--VALUES(
--    (SELECT NVL(MAX(CUS_NUM),0)+1 FROM CUS),
--    '개똥이',
--    '대전광역시 중구 123',
--    '010-123-1234'  
--);
commit


--CUS테이블 DETAIL
SELECT CUS_NUM, CUS_NM, ZIPCODE, ADDR1, ADDR2, PNE, PWD, CUS_DETAIL, CUS_IMAGE
FROM CUS
WHERE CUS_NUM = 1