CREATE TABLE GUESTBOOK_MESSAGE(
    MESSAGE_ID NUMBER,
    GUEST_NAME VARCHAR2(300),
    PASSWORD VARCHAR2(100),
    MESSAGE VARCHAR2(4000),
    CONSTRAINT PK_GUESTBOOK_MESSAGE PRIMARY KEY(MESSAGE_ID)
);