select *
from zisoom.member;

CREATE TABLE MEMBER(
    MEMBERID VARCHAR2(20),
    PASSWORD VARCHAR2(100),
    NAME VARCHAR2(90),
    EMAIL VARCHAR2(60),
    CONSTRAINT PK_MEMBER PRIMARY KEY(MEMBERID)
);    

INSERT INTO MEMBER(MEMBERID, PASSWORD, NAME, EMAIL)
SELECT MEM_ID, MEM_PASS, MEM_NAME, MEM_MAIL
FROM ZISOOM.MEMBER;

COMMIT;

SELECT *
FROM MEMBER;

CREATE TABLE MEMBER_ETC(
    MEMBERID VARCHAR2(20),
    BIRTHDAY VARCHAR2(30),
    CONSTRAINT PK_MEMBER_ETC PRIMARY KEY(MEMBERID),
    CONSTRAINT FR_MEMBER_MEMBER_ETC FOREIGN KEY(MEMBERID) REFERENCES MEMBER(MEMBERID)
);

SELECT *
FROM MEMBER A, MEMBER_ETC B
WHERE A.MEMBERID = B.MEMBERID(+);

select * from member order by memberid

update member
set name='미역은대'
where memberid = 'a001';

rollback;


