SELECT
A.COLUMN_NAME
, A.DATA_TYPE
, (SELECT B.COMMENTS FROM ALL_COL_COMMENTS B WHERE B.TABLE_NAME = A.TABLE_NAME AND B.COLUMN_NAME=A.COLUMN_NAME) COMMENTS
, '<input type=''text'' name='''||FN_GETCAMEL(COLUMN_NAME)||''' /><br />' JSP
, CASE WHEN A.DATA_TYPE='NUMBER' THEN 'private int ' || FN_GETCAMEL(A.COLUMN_NAME) || ';'
       WHEN A.DATA_TYPE IN ('VARCHAR2','CHAR') THEN 'private String ' || FN_GETCAMEL(A.COLUMN_NAME) || ';'
       WHEN A.DATA_TYPE='DATE' THEN 'private Date ' || FN_GETCAMEL(A.COLUMN_NAME) || ';'
       ELSE 'private String ' || FN_GETCAMEL(A.COLUMN_NAME) || ';'
  END AS CAMEL_CASE
, '<result column="' || COLUMN_NAME || '" property="' || FN_GETCAMEL(COLUMN_NAME) || '" />'  RESULTMAP
FROM ALL_TAB_COLUMNS A
WHERE A.TABLE_NAME = 'COUNSEL';



		SELECT
			ROW_NUMBER () OVER(ORDER BY TEST_ID DESC) RNUM
			, TEST_ID
			, TEST_TITLE
			, TEST_EXAMINER
			, TOTAL_QUEST
			, TEST_TIME
			, TO_CHAR('YYYY-MM-DD,'TEST_ST_DATE) 
			, TO_CHAR('YYYY-MM-DD,'TEST_END_DATE) 
			, OPEN_CODE1
			, SUB_CODE1
			, SUB_CODE2
			, OPEN_CODE2
		FROM TEST
		WHERE 1=1
		AND TEST_EXAMINER ='강모씨';


    	SELECT
			ROW_NUMBER () OVER(ORDER BY TEST_ID DESC) RNUM
			, TEST_ID
			, TEST_TITLE
			, TEST_EXAMINER
			, TOTAL_QUEST
			, TEST_TIME
			, TO_DATE(TEST_ST_DATE, 'YYYY-MM-DD') TEST_ST_DATE
			, TO_DATE(TEST_END_DATE, 'YYYY-MM-DD') TEST_END_DATE
			, OPEN_CODE1
			, SUB_CODE1
			, SUB_CODE2
			, OPEN_CODE2
		FROM TEST
		WHERE 1=1
		AND TEST_EXAMINER = '강모씨'

    SELECT CODEGR_ID, CODE_ID, CODEGR_NAME, CODE_NAME
    FROM CODE_TB 
    WHERE 1=1 
    AND CODEGR_ID ='S1'

        INSERT INTO TEST(TEST_ID, TEST_TITLE, TEST_EXAMINER, TOTAL_QUEST, TEST_TIME
                         ,TEST_ST_DATE, TEST_END_DATE, OPEN_CODE1, SUB_CODE1, SUB_CODE2, OPEN_CODE2)
        VALUES(
                 (SELECT NVL(MAX(TO_NUMBER(TEST_ID)),0)+1 FROM TEST), '시험', '홍길동', 50, 50 
                , '2021-02-05', '2021-02-22',(SELECT CODEGR_ID FROM CODE_TB WHERE CODE_NAME='시험 준비')
                ,'S1','S102',(SELECT CODE_ID FROM CODE_TB WHERE CODE_NAME='시험 준비')
        )   
        
        
SELECT TEST_ID, TEST_TITLE, TEST_EXAMINER, TOTAL_QUEST, TEST_TIME
        ,TEST_ST_DATE, TEST_END_DATE, OPEN_CODE1, SUB_CODE1, SUB_CODE2, OPEN_CODE2
FROM TEST          
WHERE TEST_ID = '24'  


UPDATE TEST
SET TEST_TITLE = '2월 모의고사', TOTAL_QUEST = 30, TEST_TIME = 40, TEST_ST_DATE ='2021-09-11', TEST_END_DATE ='2021-09-28', SUB_CODE2 = 'E101'
WHERE TEST_ID = '26'

COMMIT;

SELECT COUNT(*) AS CNT
		FROM TEST
		WHERE 1=1
		AND TEST_EXAMINER = '강모씨'

