commit;

SELECT QUEST_ID, QUEST_CONTENT, QUEST_ANSWER, QUEST_POINT, QUEST_TYPE, QUEST_LEVEL
				,QUEST_COMMENT, EX1, EX2, EX3, EX4, EX5, TEST_ID, QUEST_ATFILE_ID
		FROM TEST_QUEST
		WHERE TEST_ID = 13	
        ORDER BY QUEST_ID ASC;
        
        (SELECT NVL(MAX(TO_NUMBER(QUEST_ID)),0)+1 FROM TEST_QUEST WHERE TEST_ID=17)
        
        
		INSERT INTO TEST_QUEST(QUEST_ID, QUEST_CONTENT, QUEST_ANSWER, QUEST_POINT, QUEST_TYPE, QUEST_LEVEL, QUEST_COMMENT
							, EX1, EX2, EX3, EX4, TEST_ID, QUEST_ATFILE_ID)
		VALUES(1, 'dd', 'dd',5,
				's121', '상', 'ㅎㅇㅎㅇㅎ','ㅇㅇ', 'ㄴㅇㄹㅇㄹ','ㅇㄹㅇ', 'ㅇㄹㅇㄹ', 3,'' )	        
                
                SELECT NVL(MAX(TO_NUMBER(QUEST_ID)),0)+1 FROM TEST_QUEST WHERE TEST_ID= 17
                
                SELECT A.QUEST_ID, A.QUEST_CONTENT, A.QUEST_ANSWER, A.QUEST_POINT, A.QUEST_TYPE, A.QUEST_LEVEL
				,A.QUEST_COMMENT, A.EX1, A.EX2, A.EX3, A.EX4, A.EX5, A.TEST_ID, A.QUEST_ATFILE_ID, B.ATFILE_PATH
		FROM TEST_QUEST A, ATFILE B
		WHERE TEST_ID = 6
        AND QUEST_ID = 1
        AND A.QUEST_ATFILE_ID = B.ATFILE_ID

        
        
        
        		SELECT QUEST_ID, QUEST_CONTENT, QUEST_ANSWER, QUEST_POINT, QUEST_TYPE, QUEST_LEVEL, QUEST_COMMENT
				, EX1, EX2, EX3, EX4, TEST_ID, QUEST_ATFILE_ID
		FROM TEST_QUEST
		WHERE TEST_ID = 6
		AND QUEST_ID = 1

        
        
        SELECT ROW_NUMBER () OVER(ORDER BY TO_NUMBER(QUEST_ID) ASC) RNUM
             , A.QUEST_ID, A.QUEST_CONTENT, A.QUEST_ANSWER, A.QUEST_POINT, A.QUEST_TYPE, A.QUEST_LEVEL
			 , A.QUEST_COMMENT, A.EX1, A.EX2, A.EX3, A.EX4, A.TEST_ID 
        	 , A.QUEST_ATFILE_ID, B.ATFILE_PATH
		FROM TEST_QUEST A LEFT OUTER JOIN ATFILE B
		ON A.QUEST_ATFILE_ID = B.ATFILE_ID
		WHERE A.TEST_ID = 17
		ORDER BY A.QUEST_ID
        
        
        
        	SELECT A.QUEST_ID, A.QUEST_CONTENT, A.QUEST_ANSWER, A.QUEST_POINT, A.QUEST_TYPE, A.QUEST_LEVEL
                  ,A.QUEST_COMMENT, A.EX1, A.EX2, A.EX3, A.EX4, A.EX5, A.TEST_ID, A.QUEST_ATFILE_ID, B.ATFILE_PATH, B.ATFILE_ORINAME
	FROM TEST_QUEST A LEFT OUTER JOIN ATFILE B
	ON A.QUEST_ATFILE_ID = B.ATFILE_ID
    WHERE A.TEST_ID =17
	AND A.QUEST_ID = 1
    
    INSERT INTO TEST_QUEST(QUEST_ID, QUEST_CONTENT, QUEST_ANSWER, QUEST_POINT, QUEST_TYPE, QUEST_LEVEL, QUEST_COMMENT
							, EX1, EX2, EX3, EX4, TEST_ID, QUEST_ATFILE_ID)
		VALUES((SELECT NVL(MAX(TO_NUMBER(QUEST_ID)),0)+1 FROM TEST_QUEST WHERE TEST_ID= #{testId}), #{questContent}, #{questAnswer}, #{questPoint},
				#{questType}, #{questLevel}, #{questComment}, #{ex1}, #{ex2}, #{ex3}, #{ex4}, #{testId}, #{questAtfileId})
                
                
                
UPDATE TEST_QUEST
SET  QUEST_CONTENT= 'DD', QUEST_ANSWER='DD', QUEST_POINT=5, QUEST_TYPE='A401', QUEST_LEVEL='중', QUEST_COMMENT=''
    ,  EX1='D', EX2='D', EX3='SD', EX4='DFDF', QUEST_ATFILE_ID = 'DD'
WHERE TEST_ID =25
AND QUEST_ID =3

COMMIT;


DELETE FROM TEST_QUEST
		WHERE TEST_ID =17
		AND QUEST_ID =18
        
        COMMIT;



		SELECT ROW_NUMBER () OVER(ORDER BY TO_NUMBER(QUEST_ID) ASC) RNUM
			 , A.QUEST_ID, A.QUEST_CONTENT, A.QUEST_ANSWER, A.QUEST_POINT, A.QUEST_TYPE, A.QUEST_LEVEL
			 , A.QUEST_COMMENT, A.EX1, A.EX2, A.EX3, A.EX4, A.TEST_ID
			 , A.QUEST_ATFILE_ID, B.ATFILE_PATH
		FROM TEST_QUEST A LEFT OUTER JOIN ATFILE B
		ON A.QUEST_ATFILE_ID = B.ATFILE_ID
		WHERE A.TEST_ID = 17





























    
    
    